### ISSUE TITLE
What treatment could I do to transform the granulometric classes in my dataset in having phi scale intervals ?

### ISSUE THREAD

**Issue by melyym** [yuriok/QGrain#27]
Hello,

I am sorry if it is not the good place to ask such a question, but I thought it could work.
I don't have a technical software / script question but a more global one.

I understand that QGrain can't do statistical treatment with datasets not having granulometric classes spaced by same phi intervals.
Because of sample export difficulties, I could not treat some of my sediments with the same granulometry method on the field, and I had to use non standard diameters for my sieving test. 

I can treat the data in classic Gradistat excel but not in QGrain.
I think Gradistat do some interpolation to get a proper statistically good dataset from my data, but I have trouble finding which operation (maybe linear interpolation ?).

Do you have suggestions on how I could pretreat my data to correct the interval between my classes to treat it with QGrain after ?

It was worth a try and sorry for the trouble !

**Comment by yuriok** [comment]
The issue you mentioned is very common. Currently, QGrain mainly targets data measured by laser particle size analyzers, which generally have several tens to 100 sizes classes. If the data is obtained by sieve measurement, I don’t know if the number of size classes is sufficient for grain size decomposition. In theory, a simple linear interpolation can solve this problem, but it may be necessary to consider not setting the number of interpolated size classes too much beyond the measured size classes.
